#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Onion Corporation
#

USE_PROCD=1

BIN="/usr/bin/rfid-scan.sh"
  
start_service() {
        procd_open_instance
        procd_set_param command "$BIN"
        procd_set_param respawn
        procd_set_param stdout 1 # forward stdout of the command to logd
        procd_set_param stderr 1 # same for stderr
        procd_close_instance
}
